####################
#### NOT IN USE ####
####################
---
- hosts: all
  become: true
  vars:
    kafka_version: https://apache.dattatec.com/kafka/2.8.0/kafka_2.12-2.8.0.tgz
    kafka_topics:
      - input
      - output
  tasks:
  - name: Install necessary packages 
    yum:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - java-1.8.0-openjdk.x86_64

  - name: Download and Extract Kafka binaries
    unarchive: 
      src: "{{ kafka_version }}"
      dest: /home/vagrant
      remote_src: yes

  - name: Run Kafka
    shell: |
      /home/vagrant/kafka*/bin/zookeeper-server-start.sh -daemon /home/vagrant/kafka*/config/zookeeper.properties
      /home/vagrant/kafka*/bin/kafka-server-start.sh -daemon /home/vagrant/kafka*/config/server.properties
  
  - name: Create Topics
    shell: |
      /home/vagrant/kafka*/bin/kafka-topics.sh --create --zookeeper localhost:2181 --partitions 1 --topic "{{ kafka_topics [0] }}"
      /home/vagrant/kafka*/bin/kafka-topics.sh --create --zookeeper localhost:2181 --partitions 1 --topic "{{ kafka_topics [1] }}"